# Generated by Django 3.2.9 on 2021-11-20 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='導師姓名')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='聯絡電話')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='email')),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(4, '大學-實習導師'), (5, '企業-實習導師1'), (6, '企業-實習導師2')], verbose_name='分類')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_user', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '實習導師',
                'verbose_name_plural': '實習導師',
                'ordering': ('user',),
            },
        ),
    ]
