# Generated by Django 3.2.9 on 2021-11-20 03:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='發布時間')),
                ('title', models.CharField(blank=True, max_length=10, verbose_name='標題')),
                ('content', models.TextField(blank=True, verbose_name='內容')),
                ('url', models.FileField(blank=True, null=True, upload_to='message/', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='簡介必須為pdf格式')], verbose_name='檔案附件')),
            ],
            options={
                'verbose_name': '公佈欄',
                'verbose_name_plural': '公佈欄',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, '學生'), (2, '企業-人資'), (3, '管理者'), (4, '大學-實習導師'), (5, '企業-實習導師1'), (6, '企業-實習導師2')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
