# Generated by Django 3.2.9 on 2021-11-20 10:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='公司名稱')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='產業別')),
                ('uniform_numbers', models.CharField(blank=True, max_length=20, verbose_name='統一編號')),
                ('capital', models.CharField(blank=True, max_length=50, verbose_name='資本額')),
                ('employee', models.IntegerField(blank=True, default=0, verbose_name='員工數')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='公司網站')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='通訊地址')),
                ('foreign', models.CharField(blank=True, max_length=10, verbose_name='是否接受外籍生實習')),
                ('inter_ship_start', models.CharField(blank=True, max_length=15, verbose_name='實習期間 (起)')),
                ('inter_ship_end', models.CharField(blank=True, max_length=15, verbose_name='實習期間 (訖)')),
                ('work_time', models.CharField(blank=True, max_length=30, verbose_name='工作時間')),
                ('work_place', models.TextField(blank=True, verbose_name='實習地點地址')),
                ('vacancy', models.IntegerField(blank=True, default=0, verbose_name='實習名額')),
                ('salary', models.TextField(blank=True, verbose_name='薪資')),
                ('welfare', models.CharField(blank=True, max_length=20, verbose_name='其他福利')),
                ('explanation', models.CharField(blank=True, max_length=500, verbose_name='廠商說明會日期')),
                ('introduction', models.FileField(blank=True, null=True, upload_to='company/', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='簡介必須為pdf格式')], verbose_name='簡介')),
                ('interview', models.CharField(blank=True, max_length=50, verbose_name='面試方式')),
            ],
            options={
                'verbose_name': '企業資料',
                'verbose_name_plural': '企業資料',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VacancyRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='職位名稱')),
                ('required_skill', models.TextField(blank=True, verbose_name='所需專長')),
                ('number', models.IntegerField(blank=True, default=0, verbose_name='職位名額')),
                ('content', models.TextField(blank=True, verbose_name='職位內容')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancyRequirement_company', to='company.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '職缺資料',
                'verbose_name_plural': '職缺資料',
                'ordering': ('company',),
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='聯絡電話')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='email')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '企業聯絡人',
                'verbose_name_plural': '企業聯絡人',
                'ordering': ('user',),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, to='company.ContactPerson', verbose_name='企業聯絡人'),
        ),
    ]
