# Generated by Django 3.2.9 on 2021-11-20 14:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='姓名')),
                ('class_name', models.CharField(blank=True, max_length=10, verbose_name='班級')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='聯絡電話')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='email')),
                ('give_up', models.BooleanField(default=False, verbose_name='放棄名額')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '學生資料',
                'verbose_name_plural': '學生資料',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to=student.models.rename, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='履歷必須為pdf格式')], verbose_name='履歷')),
                ('company', models.ManyToManyField(blank=True, to='company.Company', verbose_name='投履的公司')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_student', to='student.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '學生履歷',
                'verbose_name_plural': '學生履歷',
                'ordering': ('student',),
            },
        ),
        migrations.CreateModel(
            name='InterShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(blank=True, max_length=20, verbose_name='實習職位')),
                ('start', models.DateField(blank=True, verbose_name='實習期間 (起)')),
                ('end', models.DateField(blank=True, verbose_name='實習期間 (訖)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_ship_company', to='company.company', verbose_name='公司')),
                ('company_tutor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inter_ship_company_tutor1', to='tutor.tutor', verbose_name='企業-實習導師1')),
                ('company_tutor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inter_ship_company_tutor2', to='tutor.tutor', verbose_name='企業-實習導師2')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_ship_student', to='student.student', verbose_name='學生')),
                ('university_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inter_ship_university_tutor', to='tutor.tutor', verbose_name='大學-實習導師')),
            ],
            options={
                'verbose_name': '實習資料',
                'verbose_name_plural': '實習資料',
                'ordering': ('student',),
            },
        ),
    ]
