# Generated by Django 3.2.9 on 2021-11-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_vacancy', models.CharField(max_length=20, verbose_name='獲得職位')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_company', to='company.company', verbose_name='公司')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_student', to='student.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '媒合結果',
                'verbose_name_plural': '媒合結果',
                'ordering': ('student',),
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_order', models.CharField(blank=True, max_length=10, null=True, verbose_name='志願序')),
                ('sort', models.CharField(max_length=10, verbose_name='正備取')),
                ('vacancy', models.CharField(max_length=100, verbose_name='應徵職位')),
                ('vacancy_result', models.CharField(blank=True, max_length=20, null=True, verbose_name='錄取職位')),
                ('review', models.CharField(blank=True, default='履歷尚未審閱', max_length=50, null=True, verbose_name='履歷審查結果')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='履歷審查回饋')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_company', to='company.company', verbose_name='公司')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_student', to='student.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '媒合資訊',
                'verbose_name_plural': '媒合資訊',
                'ordering': ('student',),
            },
        ),
    ]
