# Generated by Django 3.2.9 on 2021-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='功能身分')),
                ('function', models.CharField(max_length=20, verbose_name='功能名稱')),
                ('switch', models.BooleanField(default=False, verbose_name='開關狀態')),
            ],
            options={
                'verbose_name': '功能開關',
                'verbose_name_plural': '功能開關',
                'ordering': ('function',),
            },
        ),
    ]
