# Generated by Django 3.2.9 on 2021-11-22 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='發布時間')),
                ('title', models.CharField(blank=True, max_length=10, verbose_name='標題')),
                ('content', models.TextField(blank=True, verbose_name='內容')),
                ('url', models.FileField(blank=True, null=True, upload_to='message/', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='簡介必須為pdf格式')], verbose_name='檔案附件')),
            ],
            options={
                'verbose_name': '公佈欄',
                'verbose_name_plural': '公佈欄',
                'ordering': ('created',),
            },
        ),
    ]
